<?xml version="1.0"?>
<package format="3">
  <name>ros_control_pkg</name>
  <version>0.0.0</version>
  <description>The ros_control_pkg package</description>
  <maintainer email="zhj014@ucsd.edu">Zhenyu Jiang</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
